// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lqfpvocpetldknndoncw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxxZnB2b2NwZXRsZGtubmRvbmN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMDY5NjMsImV4cCI6MjA2MDY4Mjk2M30.shYIoOyYOaFfWPa20_HWGM9E55McPDICiPm83FygJ6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);